### ISSUE TITLE
Add Login model

### ISSUE THREAD

**Issue by marcoow** [simplabs/rails_api_auth#1]
- [x] make sure the migration is either auto generated when installing the engine or there's a rake task to generate it (not sure how that works)
- [x] the relation from the `Login` model to the `User` or whatever the host application uses must be configurable in an initializer

**Comment by oliverbarnes** [comment]
Made it so running rake db:migrate on the application will pick up the engine's migrations, as per http://pivotallabs.com/leave-your-migrations-in-your-rails-engines/ (option 3)

**Comment by marcoow** [comment]
done
