### ISSUE TITLE
Document password reset

### ISSUE THREAD

**Issue by digitalplaywright** [simplabs/rails_api_auth#12]
Currently there is no documentation on how to reset a login password.

**Comment by marcoow** [comment]
Best option would be to implement that in the demo app simplabs/rails_api_auth-demo.

**Comment by marcoow** [comment]
See the [`consume_single_use_oauth2_token!` method](http://www.rubydoc.info/github/simplabs/rails_api_auth/master/RailsApiAuth/Authentication#consume_single_use_oauth2_token%21-instance_method) and [this spec](https://github.com/simplabs/rails_api_auth/blob/master/spec/requests/access_once_spec.rb).
