### ISSUE TITLE
Allow for params to be 'dasherized'

### ISSUE THREAD

**Issue by jeffdill2** [simplabs/rails_api_auth#14]
Currently, the `Oauth2Controller` is expecting params with underscores. However, `JSONAPI::Resources` enforces dasherized params so, when trying to create a token, I keep getting the `unsupported_grant_type` error.

**Comment by marcoow** [comment]
OAuth 2.0 is it's own spec which specifies the params etc. as implemented in this engine. You cannot implement OAuth 2.0 in a way that follows JSON API.

**Comment by jeffdill2** [comment]
Ah OK. Any recommendations for the best way to implement a workaround for that on my end? My initial thought is to override the Oauth2Controller, but maybe that'd be overkill.

**Comment by marcoow** [comment]
You should change your client code so it conforms to the OAuth 2.0 spec.
