### ISSUE TITLE
Rails 5 compatibility? 

### ISSUE THREAD

**Issue by dodeja** [simplabs/rails_api_auth#25]
I am using the Rails 5 beta 1 (API Mode) and getting `Unable to load application: NameError: uninitialized constant RailsApiAuth::Authentication`

**Comment by marcoow** [comment]
We haven't tried Rails 5 yet - would be great if you could come up with a PR that fixes it!

**Comment by zaccharles** [comment]
I'm using Rails 5 beta 2 (API Mode) and I'm able to install the `rails_api_auth` gem and run `rails s` with no problems. Perhaps there was something fixed.

**Comment by marcoow** [comment]
@dodeja: does it still not work for you?

**Comment by dodeja** [comment]
@marcoow I ended up hand rolling a solution since I just needed a subset of features. Thanks for checking.

**Comment by kalmanh** [comment]
This issue should now be "fixed" after https://github.com/simplabs/rails_api_auth/commit/bae4b27c8f70d31b24fc99308131313ffc537661 commit

Otherwise, to "fix it" you simply needed to include the required files as is shown in the demo project. https://github.com/simplabs/rails_api_auth-demo/blob/master/app/controllers/authenticated_controller.rb#L1 I guess the demo project needs to be changed to be inline with the latest commit as well...

**Comment by marcoow** [comment]
@kalmanh: want to submit a PR for the demo project?

**Comment by kalmanh** [comment]
Sure. I can take care of that...

**Comment by kalmanh** [comment]
Done.

https://github.com/simplabs/rails_api_auth-demo/pull/3

**Comment by soolaimon** [comment]
How are you guys getting around this?
```
Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails (>= 5.0.0.1, ~> 5.0.0)

    rails_api_auth (~> 0.0.6) was resolved to 0.0.6, which depends on
      rails (< 5, >= 3.2.6)
```

**Comment by marcoow** [comment]
@soolaimon: want to create a PR changing the required version? We should also update the tests to run against Rails 5 as well then.

**Comment by jayvarner** [comment]
Bumping this. I'm trying to move to 5. Is someone working on this? Can I help? I'm also welling to take it on.

**Comment by marcoow** [comment]
@jayvarner: supporting Rails 5 should be mostly a matter of changing the dependency string in the gemspec and update the tests so that they run against Rails 5 as well - PR would be awesome!

**Comment by jayvarner** [comment]
@marcoow thanks for merging in my PR #57. I assume you can close this. :beers:

**Comment by marcoow** [comment]
yep, closing
