### ISSUE TITLE
Need pry as a production dependency?

### ISSUE THREAD

**Issue by kalmanh** [simplabs/rails_api_auth#30]
I deployed my app to Heroku (which runs apps in production environment) and it was not working.

The reason I believe was because pry is specified as a development dependency, but is being used in production as well

https://github.com/simplabs/rails_api_auth/search?utf8=%E2%9C%93&q=pry

Once I added pry to my app's Gemfile - the app started working fine

**Comment by fidalgo** [comment]
It seems that I have it left while developing the Google authentication support.
I will submit a  PR with the fix!

**Comment by kalmanh** [comment]
Also, I don't believe you need any `require` on top. Once in the Gemfile, the bundler should `require` it for you automatically. What was the last time you wrote `require 'active_record'`? :)

**Comment by marcoow** [comment]
fixed by #31
