### ISSUE TITLE
Uniqueness of identification

### ISSUE THREAD

**Issue by mathiasAichinger** [simplabs/rails_api_auth#35]
Hi,

I have a question to the uniqueness of the identification attribute. There is no `validates_uniqueness_of :identification` in the `Login` model and it's possible to use a email address twice. Should this be handled by the `User` model of the application?

**Comment by marcoow** [comment]
Yeah, I guess that was simply forgotten. The tokens should actually be unique as well of course. Can you prepare a pull request?

**Comment by marcoow** [comment]
closed via #45
