### ISSUE TITLE
Clarity on facebook uri

### ISSUE THREAD

**Issue by dominicfollett** [simplabs/rails_api_auth#39]
Hi I am a bit confused about the redirect uri's

```rb
 raa.facebook_redirect_uri = 'redirect_uri'
```

Which url is this? 

In addition how does the rail_api_auth gem get the authorization grant from another server?

**Comment by marcoow** [comment]
That's the redirect URI you configured on Facebook's side for your Facebook app.

Not sure what you mean wrt authorization grant. The client sends the authorization code to the Rails server which sends it to Facebook and in return gets an access token.

**Comment by dominicfollett** [comment]
Thanks, that helps. 

So in a call to localhost/token, I would include the authorization code in the payload, and then rails_api_auth would then send it to the redirect uri to get the token?

context:

I've been adding support to rails_api_auth for the Edx learning platform (on a fork), but I have just been trying to get my head around some of the stuff :)

**Comment by marcoow** [comment]
No it sends the authorization code to Facebook and includes the redirect URI in the request - see here: https://github.com/simplabs/rails_api_auth/blob/master/app/services/facebook_authenticator.rb#L9

**Comment by dominicfollett** [comment]
Thank you.
