### ISSUE TITLE
How to fetch Friends list , and basic proflie info after facebookl login?

### ISSUE THREAD

**Issue by talhaobject90** [simplabs/rails_api_auth#56]
I implemented the ember-simple-auth-torii functions on ember side, and did rails_api_auth on rails side , it's  working great , but rails_api_auth doesn't provide a method to fetch the friends list and basic profile info from the logged in profile , Is there any way with this gem? or should i use any other plugins along with rails_api_auth ?

**Comment by marcoow** [comment]
rails_api_auth uses Facebook only to verify the user's identity and does not have functionality to interact with Facebook in any other way.

**Comment by talhaobject90** [comment]
Thanks marcoww for a fast reply, Is there any other rails gem better compatible with ember-simple-auth-tori? could you suggest?
