### ISSUE TITLE
overriding Oauth2Controller is throwing error on production mode

### ISSUE THREAD

**Issue by phoenixTW** [simplabs/rails_api_auth#70]
I am trying to override Oauth2Controller given a requirement to check validity of a user before login.

```
class SessionController < RailsApiAuth::Oauth2Controller
  def create
    user = User.find_by_username(params[:username])
    if user && user[:admin]
       # do something
    else
      super
    end
  end
end
```

Where my route is `post '/access-token' => "session#create"`

While running the app on production mode, I am getting such *error* ->
```
app/controllers/session_controller.rb:19:in `<top (required)>': uninitialized constant RailsApiAuth::Oauth2Controller (NameError)
```

Is there anything missing from the implementation?

**Comment by marcoow** [comment]
It's `Oauth2Controller` actually, not `RailsApiAuth::Oauth2Controller`
