### ISSUE TITLE
Setup Travis

### ISSUE THREAD

**Issue by marcoow** [simplabs/rails_api_auth#8]
…so we have automated tests

- [x] setup travis build
- [x] setup tests so they run against all relevant rails versions
- [x] setup tests so they run rubinius and JRuby as well

**Comment by marcoow** [comment]
@oliverbarnes: maybe you can figure out why the JRuby build keeps failing - the needed gem is in the Gemfile, it just never seems to get installed (see e.g. [here](https://travis-ci.org/simplabs/rails_api_auth/jobs/72900158#L97)).

**Comment by oliverbarnes** [comment]
will do
